#:schema ./mapping_schema.json
[[tables]]
from = "objects_parquet"
to = "objects"
[[tables.columns]]
from = "oid_parquet"
to = "oid"
[[tables.columns]]
from = "firstmjd_parquet"
to = "firstmjd"
[[tables.columns]]
from = "ndet_parquet"
to = "ndet"

[[tables]]
from = "detections_parquet"
to = "detections"
[[tables.columns]]
from = "oid_parquet"
to = "oid"
[[tables.columns]]
from = "mag_parquet"
to = "mag"
[[tables.columns]]
from = "candid_parquet"
to = "candid"

[[tables]]
from = "fake_parquet"
to = "fake_table"
[[tables.columns]]
from = "fake_column_parquet"
to = "fake_column_db"
