name: test
on: pull_request
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-deps
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles("poetry.lock") }}
      - name: Install dependencies
        if: steps.cached-poetry-deps.outputs.cache-hit != "true"
        run: poetry install --no-interactive
      - name: Run tests
        run: |
          poetry run pytest tests
